"use client"

import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Manrope } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { StyleSheetManager } from "styled-components";
import isPropValid from "@emotion/is-prop-valid";

const manrope = Manrope({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <StyleSheetManager shouldForwardProp={isPropValid}>
      <html lang="en" className={manrope.className}>
        <head>
          <title>Create Next App</title>
        </head>
        <body>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </StyleSheetManager>
  );
}
