import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Manrope } from "next/font/google";
import Footer from "@/components/footer/Footer";

const manrope = Manrope({subsets:["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body >
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
